Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.provider "parallels"

  # Server 1
  config.vm.define "ubuntu_vm1" do |vm1|
    vm1.vm.hostname = "Jenkins-server"
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.provider "parallels" do |p|
      p.name = "Jenkins_Server_UB1"
    end
  end

  # Server 2
  config.vm.define "ubuntu_vm2" do |vm2|
    vm2.vm.hostname = "Jenkins-worker"
    vm2.vm.network "private_network", ip: "192.168.33.11"
    vm2.vm.provider "parallels" do |p|
      p.name = "Jenkins_worker1_UB1"
    end
  end
end

