version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:7.17.14
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  fluentd:
    build:
      context: .
      dockerfile: Dockerfile-fluentd
    container_name: fluentd
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.14
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: "nodejs-app"
        fluentd-address: "fluentd:24224"
    ports:
      - "3000:3000"
    networks:
      - default





















































































































































