version: '3.8'

services:
  app:
    build:
      context: ./gunicorn
      dockerfile: Dockerfile
    container_name: app_service
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80" 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


