Vagrant.configure("2") do |config|

    # Define variables for the whole Vagrantfile
      DB_USER = ENV['DB_USER']
      DB_PASS = ENV['DB_PASS']
      DB_NAME = ENV['DB_NAME']
      DB_HOST = ENV['DB_HOST']
      DB_PORT = ENV['DB_PORT']
      APP_USER = ENV['APP_USER']
      APP_USER_PASS = ENV['APP_USER_PASS']
      APP_DIR = ENV['APP_DIR']
      PROJECT_DIR = ENV['PROJECT_DIR']

  # Налаштування для бази даних (DB_VM)
  config.vm.define "db_vm" do |db|
    db.vm.box = "bento/ubuntu-20.04"
    db.vm.hostname = "db.local"
    db.vm.network "private_network", ip: "192.168.56.10"
    db.vm.provider "parallels" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Передача змінних середовища у Vagrantfile
    DB_USER = ENV['DB_USER']
    DB_PASS = ENV['DB_PASS']
    DB_NAME = ENV['DB_NAME']

    # Провіжінінг з використанням bash для встановлення бази даних
   db.vm.provision "shell", path: "db_setup.sh"
   db.vm.provision "shell", path: "mysql_user_setup.sh", env: {"DB_USER" => DB_USER, "DB_PASS" => DB_PASS}
   db.vm.provision "shell", path: "new_database_setup.sh", env: {"DB_USER" => DB_USER, "DB_PASS" => DB_PASS,"DB_NAME" => DB_NAME}
  end

  # Налаштування для застосунку (APP_VM)
  config.vm.define "app_vm" do |app|
    app.vm.box = "bento/ubuntu-20.04"
    app.vm.hostname = "app.local"
    app.vm.network "private_network", ip: "192.168.56.11"

    # Якщо не використовуємо приватну мережу, перенаправляємо порт 8080
    # app.vm.network "forwarded_port", guest: 8080, host: 8080

    app.vm.provider "parallels" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
    end

    # Провижининг с передачей переменных окружения
    app.vm.provision "shell", path: "app_script.sh", env: {
      "DB_HOST" => ENV['DB_HOST'],
      "DB_PORT" => ENV['DB_PORT'],
      "DB_USER" => ENV['DB_USER'],       
      "DB_PASS" => ENV['DB_PASS'],       
      "DB_NAME" => ENV['DB_NAME'],       
      "APP_USER" => ENV['APP_USER'],
      "APP_USER_PASS" => ENV['APP_USER_PASS'],
      "APP_DIR" => ENV['APP_DIR'],
      "PROJECT_DIR" => ENV['PROJECT_DIR']
    }
  end
end

